package com.assistente.inventario.model.enums;

public enum TipoEquipamento {
    NOTEBOOK,
    DESKTOP,
    IMPRESSORA,
    MONITOR,
    TECLADO,
    MOUSE,
    SWITCH,
    SERVIDOR,
    CELULAR,
    AUTOTRANSFORMADOR,
    CADEADO,
    CAMERA,
    CENTRAL_TELEFONICA,
    CONDICIONADOR_DE_AR,
    CONTROLE_DE_ACESSO,
    DISTRIBUIDOR_OPTICO,
    FIREWALL,
    LEITOR_BIOMETRICO,
    MONITOR_FID,
    NOBRAK,
    RACK,
    STORAGE,
    TBOX,
    TABLET,
    TELEFONE,
    OUTRO
}
